[tasks.format]
workspace = false
command = "cargo"
args = ["fmt", "--all"]

[tasks.create-metadata]
workspace = false
script = ["node scripts/create-metadata.js"]

[tasks.build-all]
workspace = false
dependencies = ["build-launcher", "build-app"]

[tasks.build-launcher]
workspace = false
command = "cargo"
args = ["build", "--release", "-p", "launcher"]

[tasks.build-app]
workspace = false
script = ["npm run tauri build -- --no-bundle"]

[tasks.bundle-installer]
workspace = false
command = "iscc"
args = ["installer.iss"]

[tasks.release]
workspace = false
dependencies = [
  "format",
  "build-all",
  # "bundle-installer"
]
